// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Infrastructure.Persistence;

#nullable disable

namespace Portfolio.Infrastructure.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    partial class PortfolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Domain.Entities.AnalyticsEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CvVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LinkedinVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<bool>("PortfolioVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("PublicVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("analytics_events", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CvVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("LinkedinVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<bool>("PortfolioVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("PublicVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.CertificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialUrl")
                        .HasColumnType("text");

                    b.Property<bool>("CvVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("IssuedAt")
                        .HasColumnType("text");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LinkedinVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PortfolioVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("PublicVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("certifications", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ConsentRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AnalyticsConsent")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CvVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("LinkedinVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("MarketingConsent")
                        .HasColumnType("boolean");

                    b.Property<bool>("PortfolioVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("PublicVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VisitorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("consent_records", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ContactMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CvVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("LinkedinVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PortfolioVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("PublicVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("contact_messages", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.CourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CvVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("LinkedinVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<bool>("PortfolioVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("PublicVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TitleAr")
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.EducationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CvVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("DegreeAr")
                        .HasColumnType("text");

                    b.Property<string>("DegreeEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("EndDate")
                        .HasColumnType("text");

                    b.Property<string>("FieldAr")
                        .HasColumnType("text");

                    b.Property<string>("FieldEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GraduationDate")
                        .HasColumnType("text");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LinkedinVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("PortfolioVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("PublicVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<string>("StartDate")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("educations", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ExperienceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<string>>("AchievementsAr")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("AchievementsEn")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Current")
                        .HasColumnType("boolean");

                    b.Property<bool>("CvVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndDate")
                        .HasColumnType("text");

                    b.Property<bool>("LinkedinVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int>("OrganizationType")
                        .HasColumnType("integer");

                    b.Property<bool>("PortfolioVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("PositionAr")
                        .HasColumnType("text");

                    b.Property<string>("PositionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PublicVisible")
                        .HasColumnType("boolean");

                    b.Property<List<string>>("ResponsibilitiesAr")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("ResponsibilitiesEn")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<string>("StartDate")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Technologies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("experiences", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CvVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("DemoUrl")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocsUrl")
                        .HasColumnType("text");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("text");

                    b.Property<List<string>>("FeaturesAr")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("FeaturesEn")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("integer");

                    b.Property<bool>("LinkedinVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PortfolioVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("PublicVisible")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RelatedProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryAr")
                        .HasColumnType("text");

                    b.Property<string>("SummaryEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaglineAr")
                        .HasColumnType("text");

                    b.Property<string>("TaglineEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Technologies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiUrl")
                        .HasColumnType("text");

                    b.Property<string>("ApproachAr")
                        .HasColumnType("text");

                    b.Property<string>("ApproachEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("ArchitectureAr")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("ArchitectureEn")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CvVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("DocsUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean");

                    b.Property<List<string>>("FeaturesAr")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("FeaturesEn")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("integer");

                    b.Property<bool>("LinkedinVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("LiveUrl")
                        .HasColumnType("text");

                    b.Property<List<string>>("OutcomesAr")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("OutcomesEn")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Platform")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("PortfolioVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("ProblemAr")
                        .HasColumnType("text");

                    b.Property<string>("ProblemEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PublicVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("RepoUrl")
                        .HasColumnType("text");

                    b.Property<string>("RoleAr")
                        .HasColumnType("text");

                    b.Property<string>("RoleEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryAr")
                        .HasColumnType("text");

                    b.Property<string>("SummaryEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaglineAr")
                        .HasColumnType("text");

                    b.Property<string>("TaglineEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Technologies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Timeframe")
                        .HasColumnType("text");

                    b.Property<string>("TitleAr")
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<string>>("CapabilitiesAr")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("CapabilitiesEn")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CvVisible")
                        .HasColumnType("boolean");

                    b.Property<List<string>>("DeliverablesAr")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("DeliverablesEn")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("IdealForAr")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("IdealForEn")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("LinkedinVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("PortfolioVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("PublicVisible")
                        .HasColumnType("boolean");

                    b.Property<List<string>>("RelatedProjects")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryAr")
                        .HasColumnType("text");

                    b.Property<string>("SummaryEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleAr")
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.SkillEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ContextAr")
                        .HasColumnType("text");

                    b.Property<string>("ContextEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CvVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Emphasis")
                        .HasColumnType("text");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean");

                    b.Property<bool>("LinkedinVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PortfolioVisible")
                        .HasColumnType("boolean");

                    b.Property<int?>("ProficiencyLabel")
                        .HasColumnType("integer");

                    b.Property<bool>("PublicVisible")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SkillGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SkillGroupId");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.SkillGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CvVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LabelAr")
                        .HasColumnType("text");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LinkedinVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("PortfolioVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("PublicVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("skill_groups", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.SkillEntity", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.SkillGroupEntity", "SkillGroup")
                        .WithMany("Skills")
                        .HasForeignKey("SkillGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillGroup");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.SkillGroupEntity", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
