import type { CanonicalProject } from "../schema";

/**
 * Canonical projects (Phase 4).
 *
 * Projects are proof of engineering capability. No metrics, users, revenue or
 * performance claims appear anywhere — none were verified. Unknown fields stay
 * empty rather than being filled with invented content.
 */
export const projects: CanonicalProject[] = [
  {
    id: "project-nextnext-gen-hub",
    slug: "nextnext-gen-hub",
    title: { en: "nextnext-gen.com ecosystem hub", ar: null },
    tagline: { en: "The bilingual root site for a growing product ecosystem.", ar: null },
    category: "web",
    platform: ["web"],
    lifecycle: "in-development",
    role: { en: "Designer and engineer", ar: null },
    summary: {
      en: "The root domain of the ecosystem: a bilingual (EN/AR, RTL) portfolio and product hub built on a typed, data-driven content layer so products can later ship on their own subdomains.",
      ar: null,
    },
    problem: {
      en: "Projects, products and professional information were scattered with no single canonical source.",
      ar: null,
    },
    approach: {
      en: "A typed canonical content layer behind a single access API, with locale-prefixed routes and server-rendered SEO metadata.",
      ar: null,
    },
    architecture: {
      en: [
        "TanStack Start with locale-prefixed routes",
        "Typed canonical content layer with provenance and visibility",
        "Per-route SEO metadata, hreflang and JSON-LD",
        "Dark/light theming and full RTL support",
      ],
      ar: null,
    },
    features: {
      en: ["Bilingual EN/AR with RTL", "Dark and light themes", "Project and product detail pages", "Canonical content architecture"],
      ar: null,
    },
    technologies: ["React", "TypeScript", "Vite", "Tailwind CSS", "shadcn/ui", "TanStack Router"],
    outcomes: { en: [], ar: null },
    screenshots: [],
    links: { live: "https://nextnext-gen.com" },
    featured: false,
    verified: true,
    status: "verified",
    provenance: { sourceType: "portfolio", source: "this repository" },
    visibility: { public: true, portfolio: true, cv: true, linkedin: false },
  },
  {
    id: "project-dalil-masry",
    slug: "dalil-masry",
    title: { en: "Dalil Masry — Egyptian Services Directory", ar: "دليل مصري — دليل الخدمات المصري" },
    tagline: { en: "Arabic-first services directory for Egypt.", ar: null },
    category: "web",
    platform: ["web"],
    lifecycle: "in-development",
    role: { en: "Architect and sole engineer", ar: "مهندس ومصمم المنصة" },
    summary: {
      en: "Arabic-first directory uniting services, clinics, shops and professionals across Egypt in one searchable platform.",
      ar: "دليل عربي يجمع الخدمات والعيادات والمتاجر ومقدّمي الخدمات في مصر داخل منصة واحدة قابلة للبحث.",
    },
    problem: { en: "", ar: null },
    approach: { en: "", ar: null },
    architecture: { en: [], ar: null },
    features: { en: [], ar: null },
    technologies: ["React", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL", "Vite"],
    outcomes: { en: [], ar: null },
    screenshots: [],
    links: { live: "https://dalil-masry-app.lovable.app/" },
    featured: true,
    verified: true,
    status: "verified",
    provenance: { sourceType: "portfolio", source: "portfolio content" },
    visibility: { public: true, portfolio: true, cv: true, linkedin: false },
  },
  {
    id: "project-shifa-travel",
    slug: "shifa-travel",
    title: { en: "Shifa Travel — Medical Tourism Platform", ar: "شفاء ترافل — منصة السياحة العلاجية" },
    tagline: { en: "Bilingual medical-tourism journey platform.", ar: null },
    category: "web",
    platform: ["web"],
    lifecycle: "in-development",
    role: { en: "Architect and sole engineer", ar: "مهندس ومصمم المنصة" },
    summary: {
      en: "Bilingual medical-tourism platform connecting patients with accredited centers, doctors and treatment packages with full travel coordination.",
      ar: "منصة سياحة علاجية ثنائية اللغة تربط المرضى بالمراكز الطبية والأطباء المعتمدين والباقات العلاجية مع تنسيق كامل للسفر.",
    },
    problem: { en: "", ar: null },
    approach: { en: "", ar: null },
    architecture: { en: [], ar: null },
    features: { en: [], ar: null },
    technologies: ["React", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL", "Vite"],
    outcomes: { en: [], ar: null },
    screenshots: [],
    links: { live: "https://journey-cure-haven.lovable.app/" },
    featured: true,
    verified: true,
    status: "verified",
    provenance: { sourceType: "portfolio", source: "portfolio content" },
    visibility: { public: true, portfolio: true, cv: true, linkedin: false },
  },
  {
    id: "project-wameedh-hub",
    slug: "wameedh-hub",
    title: { en: "Wameedh Hub — Learning & Professional Growth Platform", ar: "وَمِيد هَب — منصّة التعلّم والتطوير المهني" },
    tagline: { en: "Courses, coaching and skill-building in one platform.", ar: null },
    category: "web",
    platform: ["web"],
    lifecycle: "in-development",
    role: { en: "Architect and sole engineer", ar: "مهندس ومصمم المنصة" },
    summary: {
      en: "Bilingual educational platform offering courses, services and coaching to help professionals build skills and advance their careers.",
      ar: "منصة تعليمية ثنائية اللغة تقدّم الكورسات والخدمات والتدريب لمساعدة المهنيين على صقل المهارات والتقدّم المهني.",
    },
    problem: { en: "", ar: null },
    approach: { en: "", ar: null },
    architecture: { en: [], ar: null },
    features: { en: [], ar: null },
    technologies: ["React", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL", "Vite"],
    outcomes: { en: [], ar: null },
    screenshots: [],
    links: { live: "https://wameedhhub.com/" },
    featured: true,
    verified: true,
    status: "verified",
    provenance: { sourceType: "portfolio", source: "portfolio content" },
    visibility: { public: true, portfolio: true, cv: true, linkedin: false },
  },
  {
    id: "project-indusb2b",
    slug: "indusb2b",
    title: { en: "IndusB2B — Industrial B2B Marketplace", ar: "IndusB2B — سوق تجاري صناعي B2B" },
    tagline: { en: "Arabic-first industrial B2B commerce platform.", ar: null },
    category: "web",
    platform: ["web"],
    lifecycle: "in-development",
    role: { en: "Architect and sole engineer", ar: "مهندس ومصمم المنصة" },
    summary: {
      en: "Arabic-first B2B platform for construction materials and industrial tools — catalog search, supplier comparison, RFQ workflows and a daily price ticker.",
      ar: "منصة تجارية B2B عربية لمواد البناء والمعدات الصناعية — بحث في الكتالوج، مقارنة الموردين، طلب عروض أسعار، ومؤشر يومي للأسعار.",
    },
    problem: { en: "", ar: null },
    approach: { en: "", ar: null },
    architecture: { en: [], ar: null },
    features: { en: [], ar: null },
    technologies: ["React", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL", "Vite"],
    outcomes: { en: [], ar: null },
    screenshots: [],
    links: { live: "https://grand-shelf-sync.lovable.app/" },
    featured: true,
    verified: true,
    status: "verified",
    provenance: { sourceType: "portfolio", source: "portfolio content" },
    visibility: { public: true, portfolio: true, cv: true, linkedin: false },
  },
  {
    id: "project-aurea-clinic-os",
    slug: "aurea-clinic-os",
    title: { en: "Aurea Clinic OS — Aesthetic Clinic Management", ar: "Aurea Clinic OS — نظام إدارة عيادات التجميل" },
    tagline: { en: "Full operations workspace for aesthetic clinics.", ar: null },
    category: "web",
    platform: ["web"],
    lifecycle: "in-development",
    role: { en: "Architect and sole engineer", ar: "مهندس ومصمم المنصة" },
    summary: {
      en: "Operations system for aesthetic clinics — CRM, patients, appointments, treatment plans, sessions, billing, campaigns and analytics in one workspace.",
      ar: "نظام تشغيلي لعيادات التجميل — إدارة العملاء والمرضى والمواعيد وخطط العلاج والفوترة والحملات والتحليلات في مساحة عمل واحدة.",
    },
    problem: { en: "", ar: null },
    approach: { en: "", ar: null },
    architecture: { en: [], ar: null },
    features: { en: [], ar: null },
    technologies: ["React", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL", "Recharts"],
    outcomes: { en: [], ar: null },
    screenshots: [],
    links: { live: "https://clinic-artistry-os.lovable.app/" },
    featured: true,
    verified: true,
    status: "verified",
    provenance: { sourceType: "portfolio", source: "portfolio content" },
    visibility: { public: true, portfolio: true, cv: true, linkedin: false },
  },
  {
    id: "project-maison-parfum",
    slug: "maison-parfum",
    title: { en: "Maison Parfum — Luxury Fragrance E-Commerce", ar: "Maison Parfum — متجر عطور فاخرة" },
    tagline: { en: "Bilingual luxury fragrance storefront.", ar: null },
    category: "web",
    platform: ["web"],
    lifecycle: "in-development",
    role: { en: "Architect and sole engineer", ar: "مهندس ومصمم المنصة" },
    summary: {
      en: "Bilingual luxury fragrance storefront with curated collections, a custom perfume builder, cart and account flows, and an editorial brand aesthetic.",
      ar: "متجر عطور فاخر ثنائي اللغة بمجموعات منسّقة ومسار لتصميم عطر مخصص وسلة وحسابات وهوية بصرية تحريرية.",
    },
    problem: { en: "", ar: null },
    approach: { en: "", ar: null },
    architecture: { en: [], ar: null },
    features: { en: [], ar: null },
    technologies: ["React", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL", "Vite"],
    outcomes: { en: [], ar: null },
    screenshots: [],
    links: { live: "https://perfume-joy-store.lovable.app/" },
    featured: true,
    verified: true,
    status: "verified",
    provenance: { sourceType: "portfolio", source: "portfolio content" },
    visibility: { public: true, portfolio: true, cv: true, linkedin: false },
  },
  {
    id: "project-stockhub",
    slug: "stockhub",
    title: { en: "StockHub — Inventory Management System", ar: "StockHub — نظام إدارة المخازن" },
    tagline: { en: "Arabic-first warehouse and inventory system.", ar: null },
    category: "web",
    platform: ["web"],
    lifecycle: "in-development",
    role: { en: "Architect and sole engineer", ar: "مهندس ومصمم المنصة" },
    summary: {
      en: "Arabic-first warehouse and inventory system — product management with pricing, stock movement tracking and smart low-stock alerts.",
      ar: "نظام مخازن ومخزون عربي — إدارة المنتجات بالأسعار، وتتبع حركات الإدخال والإخراج، وتنبيهات ذكية عند انخفاض الكمية.",
    },
    problem: { en: "", ar: null },
    approach: { en: "", ar: null },
    architecture: { en: [], ar: null },
    features: { en: [], ar: null },
    technologies: ["React", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL", "Vite"],
    outcomes: { en: [], ar: null },
    screenshots: [],
    links: { live: "https://prod-warden.lovable.app/" },
    featured: true,
    verified: true,
    status: "verified",
    provenance: { sourceType: "portfolio", source: "portfolio content" },
    visibility: { public: true, portfolio: true, cv: true, linkedin: false },
  },
  {
    id: "project-wameed-os",
    slug: "wameed-os",
    title: { en: "Wameed OS — CRM & HR Business Operating System", ar: "Wameed OS — نظام تشغيل أعمال CRM و HR" },
    tagline: { en: "Unified CRM, HR and project operations dashboard.", ar: null },
    category: "web",
    platform: ["web"],
    lifecycle: "in-development",
    role: { en: "Architect and sole engineer", ar: "مهندس ومصمم المنصة" },
    summary: {
      en: "Unified business operating system combining CRM pipeline, client management, HR, project tracking, payments, campaigns and an AI assistant in one bilingual dashboard.",
      ar: "نظام تشغيل أعمال موحّد يجمع CRM وإدارة العملاء وHR وتتبّع المشاريع والدفعات والحملات ومساعد ذكاء اصطناعي في لوحة تحكم ثنائية اللغة.",
    },
    problem: { en: "", ar: null },
    approach: { en: "", ar: null },
    architecture: { en: [], ar: null },
    features: { en: [], ar: null },
    technologies: ["React", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL", "Vite"],
    outcomes: { en: [], ar: null },
    screenshots: [],
    links: { live: "https://wameed-flow-hub.lovable.app/" },
    featured: true,
    verified: true,
    status: "verified",
    provenance: { sourceType: "portfolio", source: "portfolio content" },
    visibility: { public: true, portfolio: true, cv: true, linkedin: false },
  },
  {
    id: "project-digital-ops-console",
    slug: "digital-ops-console",
    title: { en: "Digital Operations Console — Projects, Clients & AI Command Center", ar: "Digital Operations Console — مركز قيادة المشاريع والعملاء والذكاء الاصطناعي" },
    tagline: { en: "Multi-tenant operations command center.", ar: null },
    category: "web",
    platform: ["web"],
    lifecycle: "in-development",
    role: { en: "Architect and sole engineer", ar: "مهندس ومصمم المنصة" },
    summary: {
      en: "Multi-tenant operations command center unifying project, client, infrastructure, automation and AI-solution management behind JWT auth and Dockerized deployment.",
      ar: "مركز قيادة عمليات رقمية متعدد المستأجرين يوحّد إدارة المشاريع والعملاء والبنية التحتية والأتمتة وحلول الذكاء الاصطناعي خلف مصادقة JWT ونشر Dockerized.",
    },
    problem: { en: "", ar: null },
    approach: { en: "", ar: null },
    architecture: { en: [], ar: null },
    features: { en: [], ar: null },
    technologies: ["React", "TypeScript", "Docker", "JWT", "PostgreSQL", "Automation", "AI"],
    outcomes: { en: [], ar: null },
    screenshots: [],
    links: { live: "https://digitaloperations-pro.lovable.app/" },
    featured: true,
    verified: true,
    status: "verified",
    provenance: { sourceType: "portfolio", source: "portfolio content" },
    visibility: { public: true, portfolio: true, cv: true, linkedin: false },
  },
  {
    id: "project-scriptoria-ar",
    slug: "scriptoria-ar",
    title: { en: "Scriptoria — Arabic AI Creator Studio", ar: "Scriptoria — استوديو صناعة المحتوى بالذكاء الاصطناعي" },
    tagline: { en: "Arabic-first AI video and script generation studio.", ar: null },
    category: "web",
    platform: ["web"],
    lifecycle: "in-development",
    role: { en: "Architect and sole engineer", ar: "مهندس ومصمم المنصة" },
    summary: {
      en: "Arabic-first AI studio that turns a short brief into a ready-to-publish video ad, social reel or YouTube script — writing, dialect, voiceover and visuals included.",
      ar: "استوديو ذكاء اصطناعي عربي يحوّل وصفًا قصيرًا إلى إعلان فيديو أو ريل سوشال أو سكربت يوتيوب جاهز للنشر — نص ولهجة وصوت ومرئيات كاملة.",
    },
    problem: { en: "", ar: null },
    approach: { en: "", ar: null },
    architecture: { en: [], ar: null },
    features: { en: [], ar: null },
    technologies: ["React", "TypeScript", "Tailwind CSS", "AI", "TTS", "Arabic NLP", "Vite"],
    outcomes: { en: [], ar: null },
    screenshots: [],
    links: { live: "https://scriptoria-ar.lovable.app/" },
    featured: true,
    verified: true,
    status: "verified",
    provenance: { sourceType: "portfolio", source: "portfolio content" },
    visibility: { public: true, portfolio: true, cv: true, linkedin: false },
  },
  {
    id: "project-dev-shield-nexus",
    slug: "dev-shield-nexus",
    title: { en: "DevShield Nexus — AI Software Assurance & DevSecOps", ar: "DevShield Nexus — ضمان جودة وأمن البرمجيات بالذكاء الاصطناعي" },
    tagline: { en: "AI-powered software assurance pipeline.", ar: null },
    category: "web",
    platform: ["web"],
    lifecycle: "in-development",
    role: { en: "Architect and sole engineer", ar: "مهندس ومصمم المنصة" },
    summary: {
      en: "AI software-assurance platform analyzing sites, apps, APIs and source code in one pipeline — AI testing, security analysis, SEO intelligence, performance tuning and automated fixing.",
      ar: "منصة ضمان برمجيات بالذكاء الاصطناعي تحلّل المواقع والتطبيقات والـ APIs والكود المصدري في مسار واحد — اختبار وأمن وSEO وأداء وإصلاح آلي.",
    },
    problem: { en: "", ar: null },
    approach: { en: "", ar: null },
    architecture: { en: [], ar: null },
    features: { en: [], ar: null },
    technologies: ["React", "TypeScript", "Tailwind CSS", "AI", "LLM", "DevSecOps", "GitHub", "Vite"],
    outcomes: { en: [], ar: null },
    screenshots: [],
    links: { live: "https://dev-shield-nexus.lovable.app/" },
    featured: true,
    verified: true,
    status: "verified",
    provenance: { sourceType: "portfolio", source: "portfolio content" },
    visibility: { public: true, portfolio: true, cv: true, linkedin: false },
  },
  {
    id: "project-smart-shelf-builder",
    slug: "smart-shelf-builder",
    title: { en: "Smart Shelf Builder — AI Catalog Intelligence", ar: "Smart Shelf Builder — ذكاء الكتالوج بالذكاء الاصطناعي" },
    tagline: { en: "AI catalog intelligence from legacy files.", ar: null },
    category: "web",
    platform: ["web"],
    lifecycle: "in-development",
    role: { en: "Architect and sole engineer", ar: "مهندس ومصمم المنصة" },
    summary: {
      en: "AI catalog-intelligence platform that turns PDFs, spreadsheets and product-image folders into a branded live digital catalog — AI reads, structures, writes and translates, then auto-publishes a shareable catalog.",
      ar: "منصة ذكاء كتالوج بالذكاء الاصطناعي تحوّل ملفات PDF وجداول البيانات وصور المنتجات إلى كتالوج رقمي حي بعلامة تجارية — قراءة وهيكلة وكتابة وترجمة ثم نشر تلقائي.",
    },
    problem: { en: "", ar: null },
    approach: { en: "", ar: null },
    architecture: { en: [], ar: null },
    features: { en: [], ar: null },
    technologies: ["React", "TypeScript", "Tailwind CSS", "AI", "LLM", "OCR", "Computer Vision", "Vite"],
    outcomes: { en: [], ar: null },
    screenshots: [],
    links: { live: "https://smart-shelf-builder.lovable.app/" },
    featured: true,
    verified: true,
    status: "verified",
    provenance: { sourceType: "portfolio", source: "portfolio content" },
    visibility: { public: true, portfolio: true, cv: true, linkedin: false },
  },
];

/**
 * Architecture maturity for the Factory is recorded separately so the
 * PROVEN / IMPLEMENTED-NOT-PROVEN / NOT-COMPLETE distinction is never lost.
 */
export const factoryMaturity = {
  projectId: "project-universal-ai-software-factory",
  runtimeVersionObserved: "0.21.0",
  controlPlane: "https://factory-api.nextnext-gen.com",
  healthEndpoint: "https://factory-api.nextnext-gen.com/health",
  claims: [
    { area: "Public control-plane health endpoint", state: "PROVEN" },
    { area: "Factory tracks (backend, frontend, API contract, database, mobile, AI, QA, security, DevOps)", state: "IMPLEMENTED_NOT_PROVEN" },
    { area: "Level 4 infrastructure", state: "NOT_COMPLETE" },
    { area: "Level 5", state: "NOT_COMPLETE" },
    { area: "Production AWS trust boundary", state: "NOT_COMPLETE" },
  ],
} as const;
