/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'
import { Route as LocaleBlogRouteImport } from './routes/$locale.blog'
import { Route as LocaleCertificatesRouteImport } from './routes/$locale.certificates'
import { Route as LocaleContactRouteImport } from './routes/$locale.contact'
import { Route as LocaleCoursesRouteImport } from './routes/$locale.courses'
import { Route as LocaleCvRouteImport } from './routes/$locale.cv'
import { Route as LocaleGalleryRouteImport } from './routes/$locale.gallery'
import { Route as LocalePayRouteImport } from './routes/$locale.pay'
import { Route as LocaleProductsRouteImport } from './routes/$locale.products'
import { Route as LocaleProjectsRouteImport } from './routes/$locale.projects'
import { Route as LocaleServicesRouteImport } from './routes/$locale.services'
import { Route as LocaleSkillsRouteImport } from './routes/$locale.skills'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale.blog.index'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale.blog.$slug'
import { Route as LocaleCertificatesIndexRouteImport } from './routes/$locale.certificates.index'
import { Route as LocaleCoursesIndexRouteImport } from './routes/$locale.courses.index'
import { Route as LocaleProjectsIndexRouteImport } from './routes/$locale.projects.index'
import { Route as LocaleProjectsSlugRouteImport } from './routes/$locale.projects.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminCampaignsRouteImport } from './routes/_authenticated/admin.campaigns'
import { Route as AuthenticatedAdminCvRouteImport } from './routes/_authenticated/admin.cv'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin.gallery'
import { Route as AuthenticatedAdminLinkedinRouteImport } from './routes/_authenticated/admin.linkedin'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminPaymentMethodsRouteImport } from './routes/_authenticated/admin.payment-methods'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminProfileRouteImport } from './routes/_authenticated/admin.profile'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminSkillsRouteImport } from './routes/_authenticated/admin.skills'
import { Route as AuthenticatedAdminSocialRouteImport } from './routes/_authenticated/admin.social'
import { Route as AuthenticatedAdminContentKindRouteImport } from './routes/_authenticated/admin.content.$kind'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'
import { Route as AuthenticatedAdminContentKindIndexRouteImport } from './routes/_authenticated/admin.content.$kind.index'
import { Route as AuthenticatedAdminContentKindIdRouteImport } from './routes/_authenticated/admin.content.$kind.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogRoute = LocaleBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCertificatesRoute = LocaleCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCoursesRoute = LocaleCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCvRoute = LocaleCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGalleryRoute = LocaleGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePayRoute = LocalePayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProductsRoute = LocaleProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProjectsRoute = LocaleProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleServicesRoute = LocaleServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSkillsRoute = LocaleSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => LocaleRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleBlogRoute,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleBlogRoute,
} as any)
const LocaleCertificatesIndexRoute = LocaleCertificatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleCertificatesRoute,
} as any)
const LocaleCoursesIndexRoute = LocaleCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleCoursesRoute,
} as any)
const LocaleProjectsIndexRoute = LocaleProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleProjectsRoute,
} as any)
const LocaleProjectsSlugRoute = LocaleProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleProjectsRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCampaignsRoute =
  AuthenticatedAdminCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCvRoute = AuthenticatedAdminCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLinkedinRoute =
  AuthenticatedAdminLinkedinRouteImport.update({
    id: '/linkedin',
    path: '/linkedin',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPaymentMethodsRoute =
  AuthenticatedAdminPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProfileRoute =
  AuthenticatedAdminProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSkillsRoute =
  AuthenticatedAdminSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSocialRoute =
  AuthenticatedAdminSocialRouteImport.update({
    id: '/social',
    path: '/social',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentKindRoute =
  AuthenticatedAdminContentKindRouteImport.update({
    id: '/content/$kind',
    path: '/content/$kind',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminContentKindIndexRoute =
  AuthenticatedAdminContentKindIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminContentKindRoute,
  } as any)
const AuthenticatedAdminContentKindIdRoute =
  AuthenticatedAdminContentKindIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminContentKindRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/auth': typeof AuthRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/blog': typeof LocaleBlogRouteWithChildren
  '/$locale/certificates': typeof LocaleCertificatesRouteWithChildren
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/courses': typeof LocaleCoursesRouteWithChildren
  '/$locale/cv': typeof LocaleCvRoute
  '/$locale/gallery': typeof LocaleGalleryRoute
  '/$locale/pay': typeof LocalePayRoute
  '/$locale/products': typeof LocaleProductsRoute
  '/$locale/projects': typeof LocaleProjectsRouteWithChildren
  '/$locale/services': typeof LocaleServicesRoute
  '/$locale/skills': typeof LocaleSkillsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/cv': typeof AuthenticatedAdminCvRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/linkedin': typeof AuthenticatedAdminLinkedinRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/payment-methods': typeof AuthenticatedAdminPaymentMethodsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/admin/social': typeof AuthenticatedAdminSocialRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/certificates/': typeof LocaleCertificatesIndexRoute
  '/$locale/courses/': typeof LocaleCoursesIndexRoute
  '/$locale/projects/': typeof LocaleProjectsIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/content/$kind': typeof AuthenticatedAdminContentKindRouteWithChildren
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/admin/content/$kind/$id': typeof AuthenticatedAdminContentKindIdRoute
  '/admin/content/$kind/': typeof AuthenticatedAdminContentKindIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/cv': typeof LocaleCvRoute
  '/$locale/gallery': typeof LocaleGalleryRoute
  '/$locale/pay': typeof LocalePayRoute
  '/$locale/products': typeof LocaleProductsRoute
  '/$locale/services': typeof LocaleServicesRoute
  '/$locale/skills': typeof LocaleSkillsRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/cv': typeof AuthenticatedAdminCvRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/linkedin': typeof AuthenticatedAdminLinkedinRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/payment-methods': typeof AuthenticatedAdminPaymentMethodsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/admin/social': typeof AuthenticatedAdminSocialRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
  '/$locale/certificates': typeof LocaleCertificatesIndexRoute
  '/$locale/courses': typeof LocaleCoursesIndexRoute
  '/$locale/projects': typeof LocaleProjectsIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/admin/content/$kind/$id': typeof AuthenticatedAdminContentKindIdRoute
  '/admin/content/$kind': typeof AuthenticatedAdminContentKindIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$locale': typeof LocaleRouteWithChildren
  '/auth': typeof AuthRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/blog': typeof LocaleBlogRouteWithChildren
  '/$locale/certificates': typeof LocaleCertificatesRouteWithChildren
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/courses': typeof LocaleCoursesRouteWithChildren
  '/$locale/cv': typeof LocaleCvRoute
  '/$locale/gallery': typeof LocaleGalleryRoute
  '/$locale/pay': typeof LocalePayRoute
  '/$locale/products': typeof LocaleProductsRoute
  '/$locale/projects': typeof LocaleProjectsRouteWithChildren
  '/$locale/services': typeof LocaleServicesRoute
  '/$locale/skills': typeof LocaleSkillsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/_authenticated/admin/cv': typeof AuthenticatedAdminCvRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/linkedin': typeof AuthenticatedAdminLinkedinRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/payment-methods': typeof AuthenticatedAdminPaymentMethodsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/_authenticated/admin/social': typeof AuthenticatedAdminSocialRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/certificates/': typeof LocaleCertificatesIndexRoute
  '/$locale/courses/': typeof LocaleCoursesIndexRoute
  '/$locale/projects/': typeof LocaleProjectsIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/content/$kind': typeof AuthenticatedAdminContentKindRouteWithChildren
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/_authenticated/admin/content/$kind/$id': typeof AuthenticatedAdminContentKindIdRoute
  '/_authenticated/admin/content/$kind/': typeof AuthenticatedAdminContentKindIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/auth'
    | '/$locale/about'
    | '/$locale/blog'
    | '/$locale/certificates'
    | '/$locale/contact'
    | '/$locale/courses'
    | '/$locale/cv'
    | '/$locale/gallery'
    | '/$locale/pay'
    | '/$locale/products'
    | '/$locale/projects'
    | '/$locale/services'
    | '/$locale/skills'
    | '/admin'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/$locale/projects/$slug'
    | '/admin/announcements'
    | '/admin/blog'
    | '/admin/campaigns'
    | '/admin/cv'
    | '/admin/gallery'
    | '/admin/linkedin'
    | '/admin/media'
    | '/admin/payment-methods'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/skills'
    | '/admin/social'
    | '/$locale/blog/'
    | '/$locale/certificates/'
    | '/$locale/courses/'
    | '/$locale/projects/'
    | '/admin/'
    | '/admin/content/$kind'
    | '/api/public/media/$'
    | '/admin/content/$kind/$id'
    | '/admin/content/$kind/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/cv'
    | '/$locale/gallery'
    | '/$locale/pay'
    | '/$locale/products'
    | '/$locale/services'
    | '/$locale/skills'
    | '/$locale'
    | '/$locale/blog/$slug'
    | '/$locale/projects/$slug'
    | '/admin/announcements'
    | '/admin/blog'
    | '/admin/campaigns'
    | '/admin/cv'
    | '/admin/gallery'
    | '/admin/linkedin'
    | '/admin/media'
    | '/admin/payment-methods'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/skills'
    | '/admin/social'
    | '/$locale/blog'
    | '/$locale/certificates'
    | '/$locale/courses'
    | '/$locale/projects'
    | '/admin'
    | '/api/public/media/$'
    | '/admin/content/$kind/$id'
    | '/admin/content/$kind'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$locale'
    | '/auth'
    | '/$locale/about'
    | '/$locale/blog'
    | '/$locale/certificates'
    | '/$locale/contact'
    | '/$locale/courses'
    | '/$locale/cv'
    | '/$locale/gallery'
    | '/$locale/pay'
    | '/$locale/products'
    | '/$locale/projects'
    | '/$locale/services'
    | '/$locale/skills'
    | '/_authenticated/admin'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/$locale/projects/$slug'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/campaigns'
    | '/_authenticated/admin/cv'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/linkedin'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/payment-methods'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/profile'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/skills'
    | '/_authenticated/admin/social'
    | '/$locale/blog/'
    | '/$locale/certificates/'
    | '/$locale/courses/'
    | '/$locale/projects/'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/content/$kind'
    | '/api/public/media/$'
    | '/_authenticated/admin/content/$kind/$id'
    | '/_authenticated/admin/content/$kind/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LocaleRoute: typeof LocaleRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog': {
      id: '/$locale/blog'
      path: '/blog'
      fullPath: '/$locale/blog'
      preLoaderRoute: typeof LocaleBlogRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/certificates': {
      id: '/$locale/certificates'
      path: '/certificates'
      fullPath: '/$locale/certificates'
      preLoaderRoute: typeof LocaleCertificatesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/courses': {
      id: '/$locale/courses'
      path: '/courses'
      fullPath: '/$locale/courses'
      preLoaderRoute: typeof LocaleCoursesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/cv': {
      id: '/$locale/cv'
      path: '/cv'
      fullPath: '/$locale/cv'
      preLoaderRoute: typeof LocaleCvRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/gallery': {
      id: '/$locale/gallery'
      path: '/gallery'
      fullPath: '/$locale/gallery'
      preLoaderRoute: typeof LocaleGalleryRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/pay': {
      id: '/$locale/pay'
      path: '/pay'
      fullPath: '/$locale/pay'
      preLoaderRoute: typeof LocalePayRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/products': {
      id: '/$locale/products'
      path: '/products'
      fullPath: '/$locale/products'
      preLoaderRoute: typeof LocaleProductsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/projects': {
      id: '/$locale/projects'
      path: '/projects'
      fullPath: '/$locale/projects'
      preLoaderRoute: typeof LocaleProjectsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services': {
      id: '/$locale/services'
      path: '/services'
      fullPath: '/$locale/services'
      preLoaderRoute: typeof LocaleServicesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/skills': {
      id: '/$locale/skills'
      path: '/skills'
      fullPath: '/$locale/skills'
      preLoaderRoute: typeof LocaleSkillsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/'
      fullPath: '/$locale/blog/'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof LocaleBlogRoute
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof LocaleBlogRoute
    }
    '/$locale/certificates/': {
      id: '/$locale/certificates/'
      path: '/'
      fullPath: '/$locale/certificates/'
      preLoaderRoute: typeof LocaleCertificatesIndexRouteImport
      parentRoute: typeof LocaleCertificatesRoute
    }
    '/$locale/courses/': {
      id: '/$locale/courses/'
      path: '/'
      fullPath: '/$locale/courses/'
      preLoaderRoute: typeof LocaleCoursesIndexRouteImport
      parentRoute: typeof LocaleCoursesRoute
    }
    '/$locale/projects/': {
      id: '/$locale/projects/'
      path: '/'
      fullPath: '/$locale/projects/'
      preLoaderRoute: typeof LocaleProjectsIndexRouteImport
      parentRoute: typeof LocaleProjectsRoute
    }
    '/$locale/projects/$slug': {
      id: '/$locale/projects/$slug'
      path: '/$slug'
      fullPath: '/$locale/projects/$slug'
      preLoaderRoute: typeof LocaleProjectsSlugRouteImport
      parentRoute: typeof LocaleProjectsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/campaigns': {
      id: '/_authenticated/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cv': {
      id: '/_authenticated/admin/cv'
      path: '/cv'
      fullPath: '/admin/cv'
      preLoaderRoute: typeof AuthenticatedAdminCvRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/linkedin': {
      id: '/_authenticated/admin/linkedin'
      path: '/linkedin'
      fullPath: '/admin/linkedin'
      preLoaderRoute: typeof AuthenticatedAdminLinkedinRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payment-methods': {
      id: '/_authenticated/admin/payment-methods'
      path: '/payment-methods'
      fullPath: '/admin/payment-methods'
      preLoaderRoute: typeof AuthenticatedAdminPaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/profile': {
      id: '/_authenticated/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AuthenticatedAdminProfileRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/skills': {
      id: '/_authenticated/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AuthenticatedAdminSkillsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/social': {
      id: '/_authenticated/admin/social'
      path: '/social'
      fullPath: '/admin/social'
      preLoaderRoute: typeof AuthenticatedAdminSocialRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content/$kind': {
      id: '/_authenticated/admin/content/$kind'
      path: '/content/$kind'
      fullPath: '/admin/content/$kind'
      preLoaderRoute: typeof AuthenticatedAdminContentKindRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/content/$kind/': {
      id: '/_authenticated/admin/content/$kind/'
      path: '/'
      fullPath: '/admin/content/$kind/'
      preLoaderRoute: typeof AuthenticatedAdminContentKindIndexRouteImport
      parentRoute: typeof AuthenticatedAdminContentKindRoute
    }
    '/_authenticated/admin/content/$kind/$id': {
      id: '/_authenticated/admin/content/$kind/$id'
      path: '/$id'
      fullPath: '/admin/content/$kind/$id'
      preLoaderRoute: typeof AuthenticatedAdminContentKindIdRouteImport
      parentRoute: typeof AuthenticatedAdminContentKindRoute
    }
  }
}

interface AuthenticatedAdminContentKindRouteChildren {
  AuthenticatedAdminContentKindIdRoute: typeof AuthenticatedAdminContentKindIdRoute
  AuthenticatedAdminContentKindIndexRoute: typeof AuthenticatedAdminContentKindIndexRoute
}

const AuthenticatedAdminContentKindRouteChildren: AuthenticatedAdminContentKindRouteChildren =
  {
    AuthenticatedAdminContentKindIdRoute: AuthenticatedAdminContentKindIdRoute,
    AuthenticatedAdminContentKindIndexRoute:
      AuthenticatedAdminContentKindIndexRoute,
  }

const AuthenticatedAdminContentKindRouteWithChildren =
  AuthenticatedAdminContentKindRoute._addFileChildren(
    AuthenticatedAdminContentKindRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminCampaignsRoute: typeof AuthenticatedAdminCampaignsRoute
  AuthenticatedAdminCvRoute: typeof AuthenticatedAdminCvRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminLinkedinRoute: typeof AuthenticatedAdminLinkedinRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminPaymentMethodsRoute: typeof AuthenticatedAdminPaymentMethodsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProfileRoute: typeof AuthenticatedAdminProfileRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSkillsRoute: typeof AuthenticatedAdminSkillsRoute
  AuthenticatedAdminSocialRoute: typeof AuthenticatedAdminSocialRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminContentKindRoute: typeof AuthenticatedAdminContentKindRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminCampaignsRoute: AuthenticatedAdminCampaignsRoute,
  AuthenticatedAdminCvRoute: AuthenticatedAdminCvRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
  AuthenticatedAdminLinkedinRoute: AuthenticatedAdminLinkedinRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminPaymentMethodsRoute: AuthenticatedAdminPaymentMethodsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminProfileRoute: AuthenticatedAdminProfileRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSkillsRoute: AuthenticatedAdminSkillsRoute,
  AuthenticatedAdminSocialRoute: AuthenticatedAdminSocialRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminContentKindRoute:
    AuthenticatedAdminContentKindRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LocaleBlogRouteChildren {
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
}

const LocaleBlogRouteChildren: LocaleBlogRouteChildren = {
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
}

const LocaleBlogRouteWithChildren = LocaleBlogRoute._addFileChildren(
  LocaleBlogRouteChildren,
)

interface LocaleCertificatesRouteChildren {
  LocaleCertificatesIndexRoute: typeof LocaleCertificatesIndexRoute
}

const LocaleCertificatesRouteChildren: LocaleCertificatesRouteChildren = {
  LocaleCertificatesIndexRoute: LocaleCertificatesIndexRoute,
}

const LocaleCertificatesRouteWithChildren =
  LocaleCertificatesRoute._addFileChildren(LocaleCertificatesRouteChildren)

interface LocaleCoursesRouteChildren {
  LocaleCoursesIndexRoute: typeof LocaleCoursesIndexRoute
}

const LocaleCoursesRouteChildren: LocaleCoursesRouteChildren = {
  LocaleCoursesIndexRoute: LocaleCoursesIndexRoute,
}

const LocaleCoursesRouteWithChildren = LocaleCoursesRoute._addFileChildren(
  LocaleCoursesRouteChildren,
)

interface LocaleProjectsRouteChildren {
  LocaleProjectsSlugRoute: typeof LocaleProjectsSlugRoute
  LocaleProjectsIndexRoute: typeof LocaleProjectsIndexRoute
}

const LocaleProjectsRouteChildren: LocaleProjectsRouteChildren = {
  LocaleProjectsSlugRoute: LocaleProjectsSlugRoute,
  LocaleProjectsIndexRoute: LocaleProjectsIndexRoute,
}

const LocaleProjectsRouteWithChildren = LocaleProjectsRoute._addFileChildren(
  LocaleProjectsRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleBlogRoute: typeof LocaleBlogRouteWithChildren
  LocaleCertificatesRoute: typeof LocaleCertificatesRouteWithChildren
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleCoursesRoute: typeof LocaleCoursesRouteWithChildren
  LocaleCvRoute: typeof LocaleCvRoute
  LocaleGalleryRoute: typeof LocaleGalleryRoute
  LocalePayRoute: typeof LocalePayRoute
  LocaleProductsRoute: typeof LocaleProductsRoute
  LocaleProjectsRoute: typeof LocaleProjectsRouteWithChildren
  LocaleServicesRoute: typeof LocaleServicesRoute
  LocaleSkillsRoute: typeof LocaleSkillsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleBlogRoute: LocaleBlogRouteWithChildren,
  LocaleCertificatesRoute: LocaleCertificatesRouteWithChildren,
  LocaleContactRoute: LocaleContactRoute,
  LocaleCoursesRoute: LocaleCoursesRouteWithChildren,
  LocaleCvRoute: LocaleCvRoute,
  LocaleGalleryRoute: LocaleGalleryRoute,
  LocalePayRoute: LocalePayRoute,
  LocaleProductsRoute: LocaleProductsRoute,
  LocaleProjectsRoute: LocaleProjectsRouteWithChildren,
  LocaleServicesRoute: LocaleServicesRoute,
  LocaleSkillsRoute: LocaleSkillsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LocaleRoute: LocaleRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
