/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'
import { Route as LocaleContactRouteImport } from './routes/$locale.contact'
import { Route as LocaleCvRouteImport } from './routes/$locale.cv'
import { Route as LocaleFactoryRouteImport } from './routes/$locale.factory'
import { Route as LocaleProductsRouteImport } from './routes/$locale.products'
import { Route as LocaleProjectsRouteImport } from './routes/$locale.projects'
import { Route as LocaleServicesRouteImport } from './routes/$locale.services'
import { Route as LocaleSkillsRouteImport } from './routes/$locale.skills'
import { Route as LocaleProductsIndexRouteImport } from './routes/$locale.products.index'
import { Route as LocaleProductsSlugRouteImport } from './routes/$locale.products.$slug'
import { Route as LocaleProjectsIndexRouteImport } from './routes/$locale.projects.index'
import { Route as LocaleProjectsSlugRouteImport } from './routes/$locale.projects.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCvRoute = LocaleCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFactoryRoute = LocaleFactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProductsRoute = LocaleProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProjectsRoute = LocaleProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleServicesRoute = LocaleServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSkillsRoute = LocaleSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProductsIndexRoute = LocaleProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleProductsRoute,
} as any)
const LocaleProductsSlugRoute = LocaleProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleProductsRoute,
} as any)
const LocaleProjectsIndexRoute = LocaleProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleProjectsRoute,
} as any)
const LocaleProjectsSlugRoute = LocaleProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/cv': typeof LocaleCvRoute
  '/$locale/factory': typeof LocaleFactoryRoute
  '/$locale/products': typeof LocaleProductsRouteWithChildren
  '/$locale/projects': typeof LocaleProjectsRouteWithChildren
  '/$locale/services': typeof LocaleServicesRoute
  '/$locale/skills': typeof LocaleSkillsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/products/$slug': typeof LocaleProductsSlugRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/$locale/products/': typeof LocaleProductsIndexRoute
  '/$locale/projects/': typeof LocaleProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/cv': typeof LocaleCvRoute
  '/$locale/factory': typeof LocaleFactoryRoute
  '/$locale/services': typeof LocaleServicesRoute
  '/$locale/skills': typeof LocaleSkillsRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/products/$slug': typeof LocaleProductsSlugRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/$locale/products': typeof LocaleProductsIndexRoute
  '/$locale/projects': typeof LocaleProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/cv': typeof LocaleCvRoute
  '/$locale/factory': typeof LocaleFactoryRoute
  '/$locale/products': typeof LocaleProductsRouteWithChildren
  '/$locale/projects': typeof LocaleProjectsRouteWithChildren
  '/$locale/services': typeof LocaleServicesRoute
  '/$locale/skills': typeof LocaleSkillsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/products/$slug': typeof LocaleProductsSlugRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/$locale/products/': typeof LocaleProductsIndexRoute
  '/$locale/projects/': typeof LocaleProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/cv'
    | '/$locale/factory'
    | '/$locale/products'
    | '/$locale/projects'
    | '/$locale/services'
    | '/$locale/skills'
    | '/$locale/'
    | '/$locale/products/$slug'
    | '/$locale/projects/$slug'
    | '/$locale/products/'
    | '/$locale/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/cv'
    | '/$locale/factory'
    | '/$locale/services'
    | '/$locale/skills'
    | '/$locale'
    | '/$locale/products/$slug'
    | '/$locale/projects/$slug'
    | '/$locale/products'
    | '/$locale/projects'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/cv'
    | '/$locale/factory'
    | '/$locale/products'
    | '/$locale/projects'
    | '/$locale/services'
    | '/$locale/skills'
    | '/$locale/'
    | '/$locale/products/$slug'
    | '/$locale/projects/$slug'
    | '/$locale/products/'
    | '/$locale/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/cv': {
      id: '/$locale/cv'
      path: '/cv'
      fullPath: '/$locale/cv'
      preLoaderRoute: typeof LocaleCvRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/factory': {
      id: '/$locale/factory'
      path: '/factory'
      fullPath: '/$locale/factory'
      preLoaderRoute: typeof LocaleFactoryRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/products': {
      id: '/$locale/products'
      path: '/products'
      fullPath: '/$locale/products'
      preLoaderRoute: typeof LocaleProductsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/projects': {
      id: '/$locale/projects'
      path: '/projects'
      fullPath: '/$locale/projects'
      preLoaderRoute: typeof LocaleProjectsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services': {
      id: '/$locale/services'
      path: '/services'
      fullPath: '/$locale/services'
      preLoaderRoute: typeof LocaleServicesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/skills': {
      id: '/$locale/skills'
      path: '/skills'
      fullPath: '/$locale/skills'
      preLoaderRoute: typeof LocaleSkillsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/products/': {
      id: '/$locale/products/'
      path: '/'
      fullPath: '/$locale/products/'
      preLoaderRoute: typeof LocaleProductsIndexRouteImport
      parentRoute: typeof LocaleProductsRoute
    }
    '/$locale/products/$slug': {
      id: '/$locale/products/$slug'
      path: '/$slug'
      fullPath: '/$locale/products/$slug'
      preLoaderRoute: typeof LocaleProductsSlugRouteImport
      parentRoute: typeof LocaleProductsRoute
    }
    '/$locale/projects/': {
      id: '/$locale/projects/'
      path: '/'
      fullPath: '/$locale/projects/'
      preLoaderRoute: typeof LocaleProjectsIndexRouteImport
      parentRoute: typeof LocaleProjectsRoute
    }
    '/$locale/projects/$slug': {
      id: '/$locale/projects/$slug'
      path: '/$slug'
      fullPath: '/$locale/projects/$slug'
      preLoaderRoute: typeof LocaleProjectsSlugRouteImport
      parentRoute: typeof LocaleProjectsRoute
    }
  }
}

interface LocaleProductsRouteChildren {
  LocaleProductsSlugRoute: typeof LocaleProductsSlugRoute
  LocaleProductsIndexRoute: typeof LocaleProductsIndexRoute
}

const LocaleProductsRouteChildren: LocaleProductsRouteChildren = {
  LocaleProductsSlugRoute: LocaleProductsSlugRoute,
  LocaleProductsIndexRoute: LocaleProductsIndexRoute,
}

const LocaleProductsRouteWithChildren = LocaleProductsRoute._addFileChildren(
  LocaleProductsRouteChildren,
)

interface LocaleProjectsRouteChildren {
  LocaleProjectsSlugRoute: typeof LocaleProjectsSlugRoute
  LocaleProjectsIndexRoute: typeof LocaleProjectsIndexRoute
}

const LocaleProjectsRouteChildren: LocaleProjectsRouteChildren = {
  LocaleProjectsSlugRoute: LocaleProjectsSlugRoute,
  LocaleProjectsIndexRoute: LocaleProjectsIndexRoute,
}

const LocaleProjectsRouteWithChildren = LocaleProjectsRoute._addFileChildren(
  LocaleProjectsRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleCvRoute: typeof LocaleCvRoute
  LocaleFactoryRoute: typeof LocaleFactoryRoute
  LocaleProductsRoute: typeof LocaleProductsRouteWithChildren
  LocaleProjectsRoute: typeof LocaleProjectsRouteWithChildren
  LocaleServicesRoute: typeof LocaleServicesRoute
  LocaleSkillsRoute: typeof LocaleSkillsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleCvRoute: LocaleCvRoute,
  LocaleFactoryRoute: LocaleFactoryRoute,
  LocaleProductsRoute: LocaleProductsRouteWithChildren,
  LocaleProjectsRoute: LocaleProjectsRouteWithChildren,
  LocaleServicesRoute: LocaleServicesRoute,
  LocaleSkillsRoute: LocaleSkillsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
